export const REQUEST_HOME_SELECTION_LIST = 'REQUEST_HOME_SELECTION_LIST';
export const SUCCESS_HOME_SELECTION_LIST = 'SUCCESS_HOME_SELECTION_LIST';
export const FAILURE_HOME_SELECTION_LIST = 'FAILURE_HOME_SELECTION_LIST';

export const REQUEST_HOME_TABLE_SOURCE = 'REQUEST_HOME_TABLE_SOURCE';
export const SUCCESS_HOME_TABLE_SOURCE = 'SUCCESS_HOME_TABLE_SOURCE';
export const FAILURE_HOME_TABLE_SOURCE = 'FAILURE_HOME_TABLE_SOURCE';
